### ISSUE TITLE
Put NeutralsSOL1D in `NESO/src/nektar/NeutralsSOL1D/<src files>`

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#100]
Executable goes here.
Add xml to examples file.

**Comment by jwscook** [comment]
The source code in this directory will be something like the `.hpp` and `*.cpp` in the [nektar-driftwave](https://github.com/ExCALIBUR-NEPTUNE/nektar-driftwave) miniapp.

**Comment by oparry-ukaea** [comment]
Solver source code is now in NESO/solvers (see #108)
