### ISSUE TITLE
solver sources in directory tree

### ISSUE THREAD

**Issue by will-saunders-ukaea** [ExCALIBUR-NEPTUNE/NESO#108]
I'm thinking we should move `<neso>/src/nektar/*` to `<neso>/solvers/*` so that our example programs/solvers are not under `src`.

**Comment by jwscook** [comment]
Is this one done now?

**Comment by will-saunders-ukaea** [comment]
I propose we could either get Owens SOL or the PIC2D3V merged then remove CombinedSolver or reverse the order and just get rid of CombinedSolver first.

**Comment by jwscook** [comment]
Looks like we'll never need the combined solver? Does the SOL2D have advection diffusion and reaction altogether anyway?

**Comment by oparry-ukaea** [comment]
Other than that CMake change, the SOL solver could be merged now, if it makes things easier. I'm planning to add tests, but can do that as a separate PR.

**Comment by will-saunders-ukaea** [comment]
CombinedSolver relies on the build objects from a nektar++ install to function - this was an experiment to see if reusing the existing objects was better than having duplicated equation systems in each solver. Ideally the nektar++ solver equation objects would be combined into a shared library we could just link against.

**Comment by oparry-ukaea** [comment]
Yes, no question it would be be better to have them in a library, but for now, reusing the objects is preferable to copy-pasting the source, in my opinion.

**Comment by oparry-ukaea** [comment]
This was resolved by #131 (removed `<neso>/src/nektar`) and #116 (added `<neso>/solvers/SimpleSOL`)
