### ISSUE TITLE
Longer max line length with clang-format

### ISSUE THREAD

**Issue by oparry-ukaea** [ExCALIBUR-NEPTUNE/NESO#135]
The LLVM style's default line length seems to be 80 characters, which is code vandalism in my book :grin: 
I'd suggest 120, but could live with 100...
```
BasedOnStyle: LLVM
ColumnLimit: 120
```

**Comment by jwscook** [comment]
80 is too short. Agree should be increased to 100 or 120. Don't mind either. Let general opinion decide

**Comment by cmacmackin** [comment]
Personally I don't like lines to get too long, so I can fit two files next to each other on my screen. I wouldn't go over 100. [Black's documentation](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length) says

>You probably noticed the peculiar default line length. Black defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, [90-ish seems like the wise choice](https://youtu.be/wf-BqAjZb8M?t=260).
>
> . . . .
>
>You can also increase it, but remember that people with sight disabilities find it harder to work with line lengths exceeding 100 characters. It also adversely affects side-by-side diff review on typical screen resolutions. Long lines also make it harder to present code neatly in documentation or talk slides.

**Comment by jwscook** [comment]
Good steer Chris, we mustnt make it hard for people with sight difficulties.

So something in the range 80<X<=100.

**Comment by oparry-ukaea** [comment]
Fair enough.
I'd argue that the syntax of C++ (or any strongly typed language) is inevitably less compact than Python, so it wouldn't be crazy to use different line lengths for black and clang-format.  The points about sight disability and diff views are both reasonable ones, though.

I'd vote for 100, but if others prefer 90 or want to keep it at 80 to avoid all the 'Apply clang-format' commits, then I'm happy to back down gracefully :grin:

Couldn't work out how to embed a poll in an issue so I created one in a discussion: #149

**Comment by oparry-ukaea** [comment]
No appetite to change this; closing!
