### ISSUE TITLE
SimpleSOLTest.2D segfaults when built with optimisation

### ISSUE THREAD

**Issue by cmacmackin** [ExCALIBUR-NEPTUNE/NESO#137]
`SimpleSOLTest.2D` (contained in the `integrationTests` binary) fails with a segfault when I build it with optimisation flags (`-O2`). When building it without them (e.g., with `-DCMAKE_BUILD_TYPE=DEBUG`), it passes. This suggests there may be an uninitialised variable (or similar) somewhere. I have tested this out with the GCC build. This test segfaults for the oneAPI build when optimisation is used (the default) but I haven't checked whether it works without optimisation in that case.

**System details**
- OS: Linux Mint 21 (Ubuntu 22.04)
- Compiler: GCC 11.2.0
- SYCL implementation: hipSYCL v0.9.2
- MPI details: MPICH v4.0.2
- Hardware: CPU (Intel Icelake)

**Comment by cmacmackin** [comment]
I have now confirmed that compiling the oneAPI build without optimisation also allows the test to pass.

**Comment by cmacmackin** [comment]
I tried compiling with the address and leak sanitizers turned on and then it ran without a problem. This looks like an unpleasant bug to track down...

**Comment by oparry-ukaea** [comment]
I can reproduce this on my machine: for both toolchains, SimpleSOLTest.2D segfaults in RelWithDebInfo, but passes in Debug.

This seems to be a Nektar-Scotch issue (again).
I get no segfault for both toolchains if I either
- run the integration tests with mpi AND/OR
- Set ^scotch@6.0.4 in the specs

That's the same behaviour as I've seen in the past, but I'm not sure why it seemed to go away when James and I were testing SimpleSOL using the previous spack set up... I was definitely using Scotch 7 for that.

I think this needs to be addressed on the Nektar side (Dave Moxey said [this MR](https://gitlab.nektar.info/nektar/nektar/-/merge_requests/1462) *might* have fixed things, but suggested sticking with Scotch 6 for now).

So I propose we:
1. Set ^scotch@6.0.4 (@6 might be enough) for both toolchains
2. Create an issue to test with Scotch 7 + the latest version of Nektar when there's time

**Comment by oparry-ukaea** [comment]
^scotch@6 works for me, for both toolchains; I'll create a PR
