### ISSUE TITLE
Hermes3 in 2D in NESO

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#175]
This is going well in https://github.com/ExCALIBUR-NEPTUNE/nektar-driftplane/tree/alt-phi-calc which needs to be merged to master. 
The diffusion branch works but is fragile - merge.
 - current implementation is analogous to https://hermes3.readthedocs.io/en/latest/examples.html#blob2d-te-ti
 - still dont know units. Chris Ridgers has been asked for help.
 - move into NESO; great to see Dave Moxey contributing directly there.
 - equations are Hermes3 Te-Ti and are in the form Equations 2-6 https://excalibur-neptune.github.io/Documents/Equations_proxyapps_Equations_EquationsProxyapps24.html (this doc is already out of date and is likely wrong (speak to Wayne, Ed and John Omotani) - lets try to keep https://github.com/ExCALIBUR-NEPTUNE/Documents/tree/main/tex/equations_for_neptune_proxyapps as the single source of truth)

**Comment by jwscook** [comment]
Status update: DM is busy right now and unable to ship the 2D turbulence Te-Ti example from Hermes3

**Comment by jwscook** [comment]
@ethrelfall has this been finished in the nektar-driftplane repo?

**Comment by ethrelfall** [comment]
DM has delivered this code (is in repo) but it needs tweaking to make it work (I've started but had no time this wk).

**Comment by jwscook** [comment]
My guess is that https://github.com/ExCALIBUR-NEPTUNE/nektar-driftplane/pull/2 fixed the the problem so this can be closed.
