### ISSUE TITLE
Implement 2D Hasegawa-Wakatani in 3D into NESO

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#177]
This is no longer dependent on "Hermes3 in 2D in NESO". Plan is to get Dave Moxey contributing directly to NESO.
 - reuse as much code between 2D and 3D

**Comment by jwscook** [comment]
Ben Dudson has given us details of the 3D drift-reduced fluid equations as per https://github.com/bendudson/hermes-3/tree/master/examples/linear. We have the equations! This can go straight into NESO and not first a standalone Nektar mini-app.

**Comment by jwscook** [comment]
PR lives in https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/181
Current issue is solving for $\phi$: not likely to be unit problem; could be boundary condition.

**Comment by jwscook** [comment]
It's relatively stable but not giving sensible answers. OP judges that it's now stable enough to add particle functionality to it.

**Comment by jwscook** [comment]
Ed & Owen to go through nondimensionalisation tomorrow.

**Comment by jwscook** [comment]
Problems with the $\phi$ solve reported. Different solvers are available: petsc, mumps. These will need extra config efforts in build.

**Comment by jwscook** [comment]
Focusing on simplified Helmsolve ${\vec{ \vec D}} \nabla_\bot \phi = \omega$ which now works with 2 Dirichlet boundary conditions. This is because the "grounded" dof with all Neumann BCs is wrong post-solve, but this "grounding" functionality can be turned off. @will-saunders-ukaea knows how cos this is done in the electrostatic solve.

**Comment by will-saunders-ukaea** [comment]
https://github.com/ExCALIBUR-NEPTUNE/NESO/blob/83d9c49e54c4026379ac1739d934489f59aa8639/solvers/Electrostatic2D3V/EquationSystems/PoissonPIC.cpp#L46C42-L46C50

False disables the checks (i.e. the pinning) true enables (and it's up to the user to check the pde is well posed?).

**Comment by jwscook** [comment]
In comms with Mike Kryjak of Hermes3 fame.

**Comment by jwscook** [comment]
2D HW equations work in 3D (no parallel dynamics) for any order (tested up to 6 modes). 
Let's figure out what neutral physics is sensible and use 2DHW in 3D w/ particles as the near term milestone.

**Comment by jwscook** [comment]
1. Get the HW system working properly in 3D with the perp Laplacian & parallel dynamics (i.e. the kappa coeff becomes a derivative along the field lines)
2. Get the LAPD system going having completed (1).

**Comment by jwscook** [comment]
This is now a tidy up PR https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/209

**Comment by oparry-ukaea** [comment]
Fixed by PR #209
