### ISSUE TITLE
Port the neutral capability to Hermes3

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#178]
Can this be written to be agnostic to the dimensionality of the turbulence miniapp?

**Comment by jwscook** [comment]
Test with a drifting set of neutrals such that there is a non-zero mean momentum, which makes it easier to test for conservation.

**Comment by jwscook** [comment]
Will has described how to get the cell volume, which is the missing piece towards getting the tests running

**Comment by oparry-ukaea** [comment]
Next steps in implementation:
- Sample ion velocities using Box-Muller transform
  - particle system already has access to ion temperature (currently converted to eV)
  - Use mu=fluid v, sigma from T to pick ion velocities using something like https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform
  - Compute total momentum change and update fluid momentum source, particle velocities as before

**Comment by jwscook** [comment]
0) Already have ionisation
1) Charge exchange
2) Recombination

Stefan suggested a simulation of volume recombination whereby an equilibrium between ionisation and recombination is reached: equil for physical densities & for numbers of macroparticles.

**Comment by jwscook** [comment]
We now have an understanding the energy error in the particle re-pairing scheme for charge exchange. Figures are imminent for the report.

**Comment by jwscook** [comment]
Work on recombination is underway.

**Comment by jwscook** [comment]
Volume recombination as per Eqs 21 and 22 from Janev Section 2.1.4

**Comment by jwscook** [comment]
Currently running 2D-in-3D HW, but will explore and run in full 3D HW
