### ISSUE TITLE
Implement 3D projection / evaluation

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#187]
We need to be able to do 3D projection and evaluation in the 3D Hermes 3 NESO solver

 - implement other basis function types
 - understand dof ording

**Comment by jwscook** [comment]
Netkar++ 3d basis functions are understood (hopefully), so green flag to finish by 31st as of today.

**Comment by jwscook** [comment]
Seems to work in serial but Nektar++ won't do decomposed DisCont fields. Basis functions and serial eval / projection of Cont and DisCont fields works in serial.

**Comment by jwscook** [comment]
Segfaulting in an all to all mpi command. Something to do with numbers of elements to pass.

**Comment by jwscook** [comment]
Can be closed when https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/199 is merged

**Comment by will-saunders-ukaea** [comment]
Merged.
