### ISSUE TITLE
NESO Nektar++ shim composite capability

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#188]
We need to be able to detect whether particles are out of the grid
 - in generality need to know which composite particle has gone through (NOT REQUIRED RIGHT NOW THOUGH)
 - need to know if of f the end or if outside the outer "radial" boundary

N.B. The grid for September is a Cartesian approx of a cylinder. There are 3 composites: 1 each at the ends, and 1 for the "radial" boundary.

**Comment by jwscook** [comment]
Need to account for particles going through MPI boundary and then through a Composite in one timestep.

**Comment by jwscook** [comment]
Progress is being made

**Comment by jwscook** [comment]
Works on 1 rank, debugging on several ranks

**Comment by jwscook** [comment]
It works - PR exists and just needs merging.

**Comment by jwscook** [comment]
This is "roughly" working in 2D and works to the MAST-U mesh. Something is wrong with some mislabelled things in the mesh but will be fixed manually. This will be added as a test-asset.

**Comment by oparry-ukaea** [comment]
@JamesEdgeley has reviewed and encountered problems with NESO-Spack; @will-saunders-ukaea will check he's merged main.
