### ISSUE TITLE
3D HW in 3D

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#214]

**Comment by jwscook** [comment]
https://github.com/ExCALIBUR-NEPTUNE/nektar-driftplane/pull/2/files is how to do fluxes

**Comment by jwscook** [comment]
There is one remaining test that isn't quite right. Otherwise basically done.

**Comment by jwscook** [comment]
@oparry-ukaea are you happy for me to close this down?

**Comment by oparry-ukaea** [comment]
Not yet - still need to resolve the issue with the energy test.

**Comment by jwscook** [comment]
Owen currently working on the energy tests (and implicit timestepping for 2D and 3D separate PRs)

**Comment by jwscook** [comment]
2Din3D works. Will do 3D in 3D after NESO becomes a library.

**Comment by jwscook** [comment]
This runs but there is still an issue with the energy conservation.

**Comment by jwscook** [comment]
@oparry-ukaea can we close this?

**Comment by jwscook** [comment]
Let's merge the `hw3d` branch and open a branch to check conservation.

**Comment by jwscook** [comment]
Closed in favour of https://github.com/ExCALIBUR-NEPTUNE/NESO/issues/263
