### ISSUE TITLE
Tag 0.1.0 against Nektar 5.3.0 to make way for a 0.2.0 release against 5.4

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#216]
- [x] merge NESO https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/191
- [x] merge https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/208 
- [x] merge  https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/225 
- [x] merge dev into main
- [x] tag new release of NP
- [x] update NESO NP git submodule
- [x] update NESO-Spack git submodule
- [x] whole load of testing
- [x] tag NESO as 0.1.0 against Nektar 5.2

... next tag NESO 0.2.0 will be against Nektar 5.x

**Comment by jwscook** [comment]
This requires a 0.3.1 NESO-Particles for NESO 0.1.0
Requires a PR into NESO-Spack to conditionally apply the patch to 5.3.0 when 5.3.0 is being used in the nektar package, and ensure NESO 0.1.0 requires Nektar 5.3.0

**Comment by will-saunders-ukaea** [comment]
Created v0.3.1 - https://github.com/ExCALIBUR-NEPTUNE/NESO-Particles/releases/tag/v0.3.1

**Comment by jwscook** [comment]
Waiting for `using namespace std` fix bundled with cmake changes to be released in NESO-Particles.

**Comment by jwscook** [comment]
When NESO #191, #208 and #225 are merged then NP dev can be merged to main and the NESO NP submodule can be updated. Finally NESO can be released.

**Comment by oparry-ukaea** [comment]
#191 and #208 are merged.

**Comment by jwscook** [comment]
#225 to be merged today (hopefully)

**Comment by will-saunders-ukaea** [comment]
> [@will-saunders-ukaea](https://github.com/will-saunders-ukaea) to do the NP items on the TODO list today

https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/236

**Comment by jwscook** [comment]
Owen has run tests with gcc / hipsycl and Will has built on Archer2 and will check that the tests run.

**Comment by will-saunders-ukaea** [comment]
> Will has built on Archer2 and will check that the tests run.
Done

**Comment by jwscook** [comment]
Great - in that case we can merge, tag, and release!

**Comment by oparry-ukaea** [comment]
Resolved by #236
