### ISSUE TITLE
Update spack.yaml and/or build instructions to work with recent oneapi versions

### ISSUE THREAD

**Issue by oparry-ukaea** [ExCALIBUR-NEPTUNE/NESO#260]
Since version 2024.0, the intel-oneapi-compilers spack package no longer contains the "classic" intel compilers (see e.g. [here](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-1/spack.html#GUID-91B08A21-4146-4546-9476-F7984A945EC2))

so
```
spack load intel-oneapi-compilers@2024
spack compiler find
```
Won't generate an intel<span>@</span>x.y spec in compilers.yaml.

We could either
1. Change the build instructions to install icc etc., separately and register them with spack or 
2. Remove the %intel tags from spack.yaml

The tags were apparently added to avoid excessive memory consumption when building numpy with earlier versions of the oneapi compilers, but that no longer seems to be an issue with 2024.1.0, as far as I can tell.

I also found I needed to drop the Scotch version requirement; version 6 failed to build with intel-oneapi-compilers@2024.1.0.

**Comment by JamesEdgeley** [comment]
To add to this - you have to use at least spack 0.22 to have oneapi@2024.1.0 included in the package.py

**Comment by oparry-ukaea** [comment]
Yep, just removing them worked fine for me (and @JamesEdgeley I believe)
