### ISSUE TITLE
(Consider how to) add spack

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#3]
How will spack work? 
 - Dependencies required by the core and one or more satellite repos exist centrally (i.e. here?)
 - Dependencies unique to any one repo exists in just that repo?
 - What about a dep required by two or more satellite repo - which one "owns" that dep?
 - Keep all spack config for everything in an entirely separate repo? How do we go about updating two things at once? Can it be automated via Actions?

@will-saunders-ukaea had some thoughts on this.

**Comment by cmacmackin** [comment]
> And we'll need GH actions to make use of a docker container with all the spack deps in, otherwise it'll spend forever just building sycl.

Creating a custom docker image with spack is probably the best bet: https://spack.readthedocs.io/en/latest/containers.html

**Comment by oparry-ukaea** [comment]
Is there anything here that wasn't covered by PR #93 ? If so, perhaps we could create a more focussed issue and close this one?
