### ISSUE TITLE
Binaries not currently installed from spack install.

### ISSUE THREAD

**Issue by jwscook** [ExCALIBUR-NEPTUNE/NESO#94]
The README from PR #93 has a TODO in the installation section:

> Binaries, however, are placed in the `bin` directory at the top level of the repository. They are not currently installed. This is a bug and will likely change in future.

This issue is a reminder to come back to this at some point.

**Comment by cmacmackin** [comment]
This was fixed with #118 (guess I forgot to note it there--sorry).
